In [25]:
import numpy as np
import scipy

from scipy import io

matdata1 = scipy.io.loadmat('E:\Repositories\EE6227_GA&ML\ML_ASSIGNMENT\Data_Train(1).mat')
matdata2 = scipy.io.loadmat('E:\Repositories\EE6227_GA&ML\ML_ASSIGNMENT\Label_Train(1).mat')
matdata3 = scipy.io.loadmat('E:\Repositories\EE6227_GA&ML\ML_ASSIGNMENT\Data_test(1).mat')
print(matdata1.keys()) #前三个是.mat文件自带的，从第四个开始，选择自己需要的部分，将其保存为.txt文件
print(matdata2.keys())
print(matdata3.keys())



dict_keys(['__header__', '__version__', '__globals__', 'Data_Train'])
dict_keys(['__header__', '__version__', '__globals__', 'Label_Train'])
dict_keys(['__header__', '__version__', '__globals__', 'Data_test'])


In [26]:
data1 = matdata1["Data_Train"]
data2 = matdata2["Label_Train"]
data3 = matdata3["Data_test"]
print(data1)#打印数据表内容
print(data2)
print(data3)

[[7.7 3.8 6.7 2.2]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]
 [4.9 3.1 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.2 3.4 1.4 0.2]
 [6.3 2.5 5.  1.9]
 [6.7 3.1 4.7 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 5.6 2.4]
 [5.7 2.5 5.  2. ]
 [4.9 2.5 4.5 1.7]
 [5.6 2.8 4.9 2. ]
 [4.7 3.2 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [6.4 3.2 5.3 2.3]
 [5.  3.3 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [5.5 2.6 4.4 1.2]
 [7.4 2.8 6.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.7 1.5 0.2]
 [6.1 2.6 5.6 1.4]
 [7.2 3.  5.8 1.6]
 [6.1 2.9 4.7 1.4]
 [7.2 3.6 6.1 2.5]
 [5.4 3.9 1.7 0.4]
 [5.7 3.  4.2 1.2]
 [5.3 3.7 1.5 0.2]
 [5.7 2.8 4.1 1.3]
 [4.8 3.4 1.9 0.2]
 [6.1 3.  4.9 1.8]
 [6.8 3.2 5.9 2.3]
 [5.1 3.4 1.5 0.2]
 [6.1 2.8 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [7.3 2.9 6.3 1.8]
 [6.9 3.1 5.1 2.3]
 [6.7 3.3 5.7 2.5]
 [6.2 2.2 4.5 1.5]
 [6.3 2.5 4.9 1.5]
 [5.6 3.  4.5 1.5]
 [6.3 3.3 4.7 1.6]
 [5.6 2.9 3.6 1.3]
 [6.3 2.7 4.9 1.8]
 [5.8 2.7 5.1 1.9]
 [6.4 2.8 5.6 2.1]
 [4.8 3.  1.4 0.3]
 [5.2 3.5 1.5 0.2]
 [4.9 3.  1.4 0.2]
 [5.5 2.4 3.8 1.1]
 [6.2 2.9 4.3 1.3]
 [5.2 4.1 1.

In [27]:
#保存
save_path1 = "E:\Repositories\EE6227_GA&ML\ML_ASSIGNMENT\Data_Train(1).txt"
save_path2 = "E:\Repositories\EE6227_GA&ML\ML_ASSIGNMENT\Label_Train(1).txt"
save_path3 = "E:\Repositories\EE6227_GA&ML\ML_ASSIGNMENT\Data_test(1).txt"
np.savetxt(save_path1,data1,fmt='%s')
np.savetxt(save_path2,data2,fmt='%s')
np.savetxt(save_path3,data3,fmt='%s')