# 1.张量的数据类型

In [58]:
#导入需要的库
import torch

In [59]:
#获取张量的数据类型
torch.tensor([1.2,3.4]).dtype

torch.float64

In [60]:
#张量的默认数据类型设置为其他类型
torch.set_default_dtype(torch.float64)
torch.tensor([1.2,3.4]).dtype
#注意：set_default_dtype()只支持设置浮点类型数据

torch.float64

In [61]:
##将张量数据类型转化为整形
a=torch.tensor([1.2,3.4])
print("a.dtype:",a.dtype)
print("a.long()方法:",a.long().dtype)
print("a.int()方法:",a.int().dtype)
print("a.float()方法:",a.float().dtype)

a.dtype: torch.float64
a.long()方法: torch.int64
a.int()方法: torch.int32
a.float()方法: torch.float32


In [63]:
#恢复torch默认的数据类型
torch.set_default_tensor_type(torch.FloatTensor)
torch.tensor([1.2,3.4]).dtype

torch.float32

In [64]:
#获取默认的数据类型
torch.get_default_dtype()

torch.float32

# 2.生成张量

### 2.1基本方法

In [2]:
import torch
A = torch.tensor([[1.0,1.0],[2,2]])
A

tensor([[1., 1.],
        [2., 2.]])

In [5]:
## 获取张量的形状
A.shape
A.size()

torch.Size([2, 2])

In [6]:
## 获取张量的形状
A.size()

torch.Size([2, 2])

In [7]:
## 计算张量中所含元素的个数
A.numel()

4

In [10]:
## 指定张量的数据类型和是否计算梯度
B = torch.tensor((1,2,3),dtype=torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

In [36]:
## 因为张量B是可以计算梯度的，所以可以计算sum(B^2)的梯度
y = B.pow(2).sum()
print(y)
y.backward()
B.grad #每一次的梯度会加上之前得到的梯度

tensor(14., grad_fn=<SumBackward0>)


tensor([ 42.,  84., 126.])

In [27]:
## 注意只有浮点类型的张量才允许计算梯度
B = torch.tensor((1,2,3),dtype=torch.int32,requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [37]:
## 利用torch.Tensor()获得张量
C = torch.Tensor([1,2,3,4])
C

tensor([1., 2., 3., 4.])

In [62]:
## 创建具有特定大小的张量
D = torch.Tensor(2,3)
D

tensor([[8.5764e-07, 1.2801e-11, 2.1029e+20],
        [5.4885e-05, 8.4936e+20, 3.1986e+21]])

In [63]:
## 创建与另一个张量大小和类型相同的张量
torch.ones_like(D)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [65]:
torch.zeros_like(D)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [69]:
torch.rand_like(D)

tensor([[0.8906, 0.1025, 0.3625],
        [0.4898, 0.1541, 0.6386]])

In [72]:
## 创建一个类型相似但尺寸不同的张量
E = [[1,2],[3,4]]
#print("E.dtype:",E.dtype)
#E 目前是一个list
E = D.new_tensor(E)
print("D.dtype:",D.dtype)
print("E.dtype:",E.dtype)
#E 编程一个tensor
E

D.dtype: torch.float32
E.dtype: torch.float32


tensor([[1., 2.],
        [3., 4.]])

In [76]:
D.new_full((3,3),fill_value = 1)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [77]:
D.new_zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [75]:
D.new_empty((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 2.2利用numpy数组生成张量

In [99]:
import numpy as np
F = np.ones((3,3))
print(F)
##使用torch.as_tensor()函数
Ftensor = torch.as_tensor(F)
Ftensor

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [101]:
## 使用torch.from_numpy()函数
Ftensor = torch.from_numpy(F)
Ftensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [103]:
## 使用张量的.numpy()将张量转化为numpy数组
Ftensor.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 设置随机数种子

In [104]:
## 设置随机数种子
torch.manual_seed(123)

In [122]:
## 通过指定均值和标准差生成随机数
torch.manual_seed(123)
A = torch.normal(mean = 0.0,std = torch.tensor(1.0))
A

tensor(-0.1115)

In [9]:
## 通过指定均值和标准差生成随机数
import torch
torch.manual_seed(123)
A = torch.normal(mean = torch.tensor(0.0),std = 1.0)
A

tensor(-0.1115)