# 1.张量的数据类型

In [58]:
#导入需要的库
import torch

In [59]:
#获取张量的数据类型
torch.tensor([1.2,3.4]).dtype

torch.float64

In [60]:
#张量的默认数据类型设置为其他类型
torch.set_default_dtype(torch.float64)
torch.tensor([1.2,3.4]).dtype
#注意：set_default_dtype()只支持设置浮点类型数据

torch.float64

In [61]:
##将张量数据类型转化为整形
a=torch.tensor([1.2,3.4])
print("a.dtype:",a.dtype)
print("a.long()方法:",a.long().dtype)
print("a.int()方法:",a.int().dtype)
print("a.float()方法:",a.float().dtype)

a.dtype: torch.float64
a.long()方法: torch.int64
a.int()方法: torch.int32
a.float()方法: torch.float32


In [63]:
#恢复torch默认的数据类型
torch.set_default_tensor_type(torch.FloatTensor)
torch.tensor([1.2,3.4]).dtype

torch.float32

In [64]:
#获取默认的数据类型
torch.get_default_dtype()

torch.float32

# 2.生成张量

### 2.1基本方法

In [2]:
import torch
A = torch.tensor([[1.0,1.0],[2,2]])
A

tensor([[1., 1.],
        [2., 2.]])

In [5]:
## 获取张量的形状
A.shape
A.size()

torch.Size([2, 2])

In [6]:
## 获取张量的形状
A.size()

torch.Size([2, 2])

In [7]:
## 计算张量中所含元素的个数
A.numel()

4

In [10]:
## 指定张量的数据类型和是否计算梯度
B = torch.tensor((1,2,3),dtype=torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

In [36]:
## 因为张量B是可以计算梯度的，所以可以计算sum(B^2)的梯度
y = B.pow(2).sum()
print(y)
y.backward()
B.grad #每一次的梯度会加上之前得到的梯度

tensor(14., grad_fn=<SumBackward0>)


tensor([ 42.,  84., 126.])

In [27]:
## 注意只有浮点类型的张量才允许计算梯度
B = torch.tensor((1,2,3),dtype=torch.int32,requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [37]:
## 利用torch.Tensor()获得张量
C = torch.Tensor([1,2,3,4])
C

tensor([1., 2., 3., 4.])

In [62]:
## 创建具有特定大小的张量
D = torch.Tensor(2,3)
D

tensor([[8.5764e-07, 1.2801e-11, 2.1029e+20],
        [5.4885e-05, 8.4936e+20, 3.1986e+21]])

In [63]:
## 创建与另一个张量大小和类型相同的张量
torch.ones_like(D)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [65]:
torch.zeros_like(D)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [69]:
torch.rand_like(D)

tensor([[0.8906, 0.1025, 0.3625],
        [0.4898, 0.1541, 0.6386]])

In [72]:
## 创建一个类型相似但尺寸不同的张量
E = [[1,2],[3,4]]
#print("E.dtype:",E.dtype)
#E 目前是一个list
E = D.new_tensor(E)
print("D.dtype:",D.dtype)
print("E.dtype:",E.dtype)
#E 编程一个tensor
E

D.dtype: torch.float32
E.dtype: torch.float32


tensor([[1., 2.],
        [3., 4.]])

In [76]:
D.new_full((3,3),fill_value = 1)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [77]:
D.new_zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [75]:
D.new_empty((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 2.2利用numpy数组生成张量

In [99]:
import numpy as np
F = np.ones((3,3))
print(F)
##使用torch.as_tensor()函数
Ftensor = torch.as_tensor(F)
Ftensor

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [101]:
## 使用torch.from_numpy()函数
Ftensor = torch.from_numpy(F)
Ftensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [103]:
## 使用张量的.numpy()将张量转化为numpy数组
Ftensor.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 2.3设置随机数种子

In [104]:
## 设置随机数种子
torch.manual_seed(123)

In [122]:
## 通过指定均值和标准差生成随机数
torch.manual_seed(123)
A = torch.normal(mean = 0.0,std = torch.tensor(1.0))
A

tensor(-0.1115)

In [1]:
## 通过指定均值和标准差生成随机数
import torch
torch.manual_seed(123)
A = torch.normal(mean = torch.tensor(0.0),std = 1.0)
A

tensor(-0.1115)

In [7]:
## 通过指定均值和标准差生成随机数
torch.manual_seed(123)
A = torch.normal(mean = 0.0, std=torch.arange(1,5.0))#不包含END 
B = torch.normal(mean = 0.0, std=torch.range(1,5.0))#包含END
print(A)
print(A.dtype)
print(B)
print(B.dtype)

tensor([-0.1115,  0.2407, -1.1089, -0.9617])
torch.float32
tensor([-1.1969,  0.4185, -2.9171, -3.0202,  1.6195])
torch.float32


e:\anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  after removing the cwd from sys.path.


In [8]:
## 在区间（0,1）上生成服从均匀分布的张量
torch.manual_seed(123)
B = torch.rand(3,4)
B

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

In [9]:
# 生成和其他张量尺寸相同的随机数张量
torch.manual_seed(123)
C = torch.ones(2,3)
D = torch.rand_like(C)
D

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [10]:
## 生成服从标准正态分布的随机数
print(torch.randn(3,3))
print(torch.randn_like(C))

tensor([[ 0.9447,  0.6217, -1.3501],
        [-0.1881, -2.3891, -0.4759],
        [ 1.7603,  0.6547,  0.5490]])
tensor([[ 0.3671,  0.1219,  0.6466],
        [-1.4168,  0.8429, -0.6307]])


In [23]:
## 将0~10(不包括10)之间的整数随机排序
torch.manual_seed(123)
torch.randperm(10)


tensor([2, 0, 8, 1, 3, 7, 4, 9, 5, 6])

### 2.4其他生成张量的函数

In [24]:
## 使用torch.arange()生成张量
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [32]:
## 在范围内生成固定数量的等间隔张量
torch.linspace(start=1,end=10,steps=5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [33]:
## 生成以对数间隔的点
torch.logspace(start=0.1,end=1.0,steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [38]:
10**torch.linspace(start=0.1,end=1.0,steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [39]:
torch.linspace(start=0.1,end=1.0,steps=5)

tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])

In [45]:
#torch.zeros(3,3)
#torch.ones(3,3)
torch.eye(3)
#torch.empty(3,3)
#torch.full((3,3),fill_value=0.25)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# 3.张量的操作

### 3.1改变张量的尺寸

In [61]:
## 使用tensor.reshape()函数设置张量的尺寸
A = torch.arange(12.0).reshape(3,4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [59]:
## 使用torch.reshape()
torch.reshape(input=A, shape=(2,-1))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [62]:
## 使用resize_方法
A.resize_(2,6)
A

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [65]:
## 使用
B = torch.arange(10.0,19.0).reshape(3,3)
B
A.resize_as_(B)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [66]:
B

tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [69]:
## torch.unsqueeze()返回在指定维度插入尺寸为1的新张量
A=torch.arange(12.0).reshape(2,6)
B=torch.unsqueeze(A,dim=0)
print(B.shape)
B

torch.Size([1, 2, 6])


tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.]]])

In [81]:
## torch.squeeze()函数移除所有维度为1的维度
C= B.unsqueeze(dim=3)
print("C.shape:",C.shape)
#print(C)
D= torch.squeeze(C)
print("D.shape:",D.shape)
print(D)
## 移除指定维度为1的维度
E = torch.squeeze(C,dim=0)
print("E.shape:",E.shape)
print(E)

C.shape: torch.Size([1, 2, 6, 1])
D.shape: torch.Size([2, 6])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
E.shape: torch.Size([2, 6, 1])
tensor([[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.]]])


In [84]:
## 使用.expand()方法拓展张量

A=torch.arange(3)
A
B=A.expand(3,-1)
B

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [85]:
## 使用expand_as()方法拓展张量
C= torch.arange(6).reshape(2,3)
B= A.expand_as(C)
B

tensor([[0, 1, 2],
        [0, 1, 2]])

In [87]:
## 使用.repeat()方法拓展张量
## B的shape是(2,3)，首先扩展橙(1,2,3)再按照repeat重复变为(1,4,6)
D= B.repeat(1,2,2)
print(D)
print(D.shape)


tensor([[[0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2]]])
torch.Size([1, 4, 6])


### 3.2获取张量中的元素

In [91]:
## 利用切片和索引获取张量中的元素
A = torch.arange(12).reshape(1,3,4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [92]:
A[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [93]:
## 获取第0维度下的矩阵前两行元素
A[0,0:2,:]

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [95]:
## 获取第0维度下的矩阵，最后一行-4~-1列
A[0,-1,-4:-1]

tensor([ 8,  9, 10])

In [96]:
## 根据条件筛选
B=-A
torch.where(A>5,A,B)

tensor([[[ 0, -1, -2, -3],
         [-4, -5,  6,  7],
         [ 8,  9, 10, 11]]])

In [97]:
## 获取A中某个元素
A[0,2,3]

tensor(11)

In [98]:
## 获取矩阵张量的下三角部分
torch.tril(A,diagonal=0)

tensor([[[ 0,  0,  0,  0],
         [ 4,  5,  0,  0],
         [ 8,  9, 10,  0]]])

In [99]:
## diagonal参数控制对角线从哪个元素开始
torch.tril(A,diagonal=1)

tensor([[[ 0,  1,  0,  0],
         [ 4,  5,  6,  0],
         [ 8,  9, 10, 11]]])

In [100]:
## 获取矩阵张量的上三角部分
torch.triu(A,diagonal=0)

tensor([[[ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  0, 10, 11]]])

In [101]:
torch.triu(A,diagonal=1)

tensor([[[ 0,  1,  2,  3],
         [ 0,  0,  6,  7],
         [ 0,  0,  0, 11]]])

In [102]:
## 获取矩阵张量的上三角部分，input,需要是一个二维的张量
C = A.reshape(3,4)
print(C)
print(torch.diag(C,diagonal=0))
print(torch.diag(C,diagonal=1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 0,  5, 10])
tensor([ 1,  6, 11])


In [103]:
## 提供对角线元素生成矩阵张量
torch.diag(torch.tensor([1,2,3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

### 3.3张量的拼接和拆分

In [144]:
## 在给定维度中连接给定的张量序列
A = torch.arange(6.0).reshape(2,3)
B = torch.linspace(0,10,6).reshape(2,3)
## 在0维度连接张量
C = torch.cat((A,B),dim=0)
C

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [108]:
## 在1维度连接张量
D = torch.cat((A,B),dim=1)
D

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]])

In [111]:
## 在1维度连接3个张量
E = torch.cat((A[:,1:3],A,B),dim=1)## A[:,1:3]表示A张量0维全部，1维元素1~2
E

tensor([[ 1.,  2.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 4.,  5.,  3.,  4.,  5.,  6.,  8., 10.]])

In [153]:
## 沿着新维度连接张量
F = torch.stack((A,B),dim=1)
print(F)
F.shape ## 两个2x3的矩阵组合在一起

tensor([[[ 0.,  1.,  2.],
         [ 0.,  2.,  4.]],

        [[ 3.,  4.,  5.],
         [ 6.,  8., 10.]]])


torch.Size([2, 2, 3])

In [122]:
G = torch.stack((A,B),dim=2)
print(G)
G.shape

tensor([[[[1, 2],
          [1, 3]],

         [[3, 4],
          [3, 5]]],


        [[[5, 6],
          [5, 7]],

         [[7, 8],
          [7, 9]]]])


torch.Size([2, 2, 2, 2])

In [123]:
## 将张量分割为特定数量的块
## 在行上将张量E分为两块
torch.chunk(E,2,dim=0)

(tensor([[1., 2., 0., 1., 2., 0., 2., 4.]]),
 tensor([[ 4.,  5.,  3.,  4.,  5.,  6.,  8., 10.]]))

In [136]:
D1,D2=torch.chunk(E,2,dim=1)
print(D1)
print(D2)

tensor([[1., 2., 0., 1.],
        [4., 5., 3., 4.]])
tensor([[ 2.,  0.,  2.,  4.],
        [ 5.,  6.,  8., 10.]])


In [139]:
## 如果沿给定维度dim的张量大小不能被整除，则最后一个块将最小
E1,E2,E3=torch.chunk(E,3,dim=1)
print(E1)
print(E2)
print(E3)

tensor([[1., 2., 0.],
        [4., 5., 3.]])
tensor([[1., 2., 0.],
        [4., 5., 6.]])
tensor([[ 2.,  4.],
        [ 8., 10.]])


In [154]:
## 将张量切分为块，指定每块的大小
D1,D2,D3=torch.split(D,[1,2,3],dim=1)
print(D1)
print(D2)
print(D3)

tensor([[0.],
        [3.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


### 3.4张量计算 比较大小

In [155]:
## 比较两个数是否接近
A = torch.tensor([10.0])
B = torch.tensor([10.1])
print(torch.allclose(A,B,rtol=1e-05,atol=1e-08,equal_nan=False))
print(torch.allclose(A,B,rtol=0.1,atol=0.01,equal_nan=False))

False
True


In [160]:
## 计算元素是否相等
A = torch.tensor([1,2,3,4,5,6])
B = torch.arange(1,7)
C = torch.unsqueeze(B,dim=0)
print(C)
# torch.eq()是比较内部的元素
print(torch.eq(A,B))
print(torch.eq(A,C))

tensor([[1, 2, 3, 4, 5, 6]])
tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


In [161]:
## 判断两个张量是否具有相同的尺寸和元素
print(torch.equal(A,B))
print(torch.equal(A,C))

True
False


In [162]:
## 逐元素比较大于等于
print(torch.ge(A,B))
print(torch.ge(A,C))

tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


In [163]:
## 大于
print(torch.gt(A,B))
print(torch.gt(A,C))

tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


In [164]:
## 小于等于/小于
print(torch.le(A,B))
print(torch.lt(A,C))

tensor([True, True, True, True, True, True])
tensor([[False, False, False, False, False, False]])


In [165]:
## 不等于
print(torch.ne(A,B))
print(torch.ne(A,C))

tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


In [166]:
## 判断是否为缺失值
torch.isnan(torch.tensor([0,1,float("nan"),2]))

tensor([False, False,  True, False])

### 3.5基本运算

In [169]:
## 矩阵逐元素相乘
A = torch.arange(6.0).reshape(2,3)
B = torch.linspace(10,20,6).reshape(2,3)
print("A:",A)
print("B:",B)
print(A*B)
##逐元素相除
print(A/B)

A: tensor([[0., 1., 2.],
        [3., 4., 5.]])
B: tensor([[10., 12., 14.],
        [16., 18., 20.]])
tensor([[  0.,  12.,  28.],
        [ 48.,  72., 100.]])
tensor([[0.0000, 0.0833, 0.1429],
        [0.1875, 0.2222, 0.2500]])


In [172]:
## 逐元素相加
print(A+B)
## 逐元素相减
print(A-B)
## 逐元素相除
print(B/A)

tensor([[10., 13., 16.],
        [19., 22., 25.]])
tensor([[-10., -11., -12.],
        [-13., -14., -15.]])
tensor([[    inf, 12.0000,  7.0000],
        [ 5.3333,  4.5000,  4.0000]])


In [173]:
## 张量的幂
print(torch.pow(A,3))
print(A**3)

tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])
tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])


In [174]:
## 张量的指数
torch.exp(A)

tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5981, 148.4132]])

In [175]:
## 张量的对数
torch.log(A)

tensor([[  -inf, 0.0000, 0.6931],
        [1.0986, 1.3863, 1.6094]])

In [176]:
## 张量的平方根
print(torch.sqrt(A))
print(A**0.5)

tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])


In [177]:
## 张量的平方根倒数
print(torch.rsqrt(A))
print(1/A**0.5)

tensor([[   inf, 1.0000, 0.7071],
        [0.5774, 0.5000, 0.4472]])
tensor([[   inf, 1.0000, 0.7071],
        [0.5774, 0.5000, 0.4472]])
